#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["APIRest/APIRest.csproj", "APIRest/"]
RUN dotnet restore "APIRest/APIRest.csproj"
COPY . .
WORKDIR "/src/APIRest"
RUN dotnet build "APIRest.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "APIRest.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:8080

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "APIRest.dll"]